import Web3 from 'web3';
import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * Quick Address Recovery Script
 * 
 * This script recovers private keys for addresses generated by BSCService.generateUserWallet()
 * It uses a reverse lookup approach to find the userId for each address.
 */

interface AddressData {
  bsc_wallet_address: string;
  bnb_balance: number;
  usdt_balance: number;
  status: string;
}

interface RecoveredAddress {
  userId: number;
  address: string;
  privateKey: string;
  bnbBalance: number;
}

class QuickRecovery {
  private web3: Web3;
  private walletSeed: string;

  constructor(walletSeed: string = 'default-seed') {
    const rpcUrl = "https://data-seed-prebsc-1-s1.binance.org:8545/";
    this.web3 = new Web3(rpcUrl);
    this.walletSeed = walletSeed;
    console.log(`Recovery initialized with seed: "${walletSeed}"\n`);
  }

  /**
   * Generate address from userId (same logic as BSCService)
   */
  private generateAddressFromUserId(userId: number): { address: string; privateKey: string } {
    const seed = `${userId}-${this.walletSeed}`;
    const hash = crypto.createHash('sha256').update(seed).digest('hex');
    const account = this.web3.eth.accounts.privateKeyToAccount('0x' + hash);
    return {
      address: account.address,
      privateKey: account.privateKey
    };
  }

  /**
   * Create a lookup map of addresses to userIds
   * This is much faster than searching for each address individually
   */
  private createAddressMap(maxUserId: number): Map<string, { userId: number; privateKey: string }> {
    console.log(`Creating address map for userIds 1-${maxUserId}...`);
    const addressMap = new Map<string, { userId: number; privateKey: string }>();
    
    for (let userId = 1; userId <= maxUserId; userId++) {
      const { address, privateKey } = this.generateAddressFromUserId(userId);
      addressMap.set(address.toLowerCase(), { userId, privateKey });
      
      if (userId % 5000 === 0) {
        console.log(`  Generated ${userId} addresses...`);
      }
    }
    
    console.log(`✓ Address map created with ${addressMap.size} addresses\n`);
    return addressMap;
  }

  /**
   * Recover addresses from JSON file
   */
  async recoverFromFile(
    filePath: string,
    maxUserId: number = 10000,
    walletSeed?: string
  ): Promise<RecoveredAddress[]> {
    try {
      // Update seed if provided
      if (walletSeed) {
        this.walletSeed = walletSeed;
        console.log(`Updated seed to: "${walletSeed}"\n`);
      }

      console.log(`Reading addresses from: ${filePath}`);
      const fileContent = fs.readFileSync(filePath, 'utf-8');
      const addresses: AddressData[] = JSON.parse(fileContent);
      
      // Filter addresses with BNB balance > 0
      const addressesWithBalance = addresses.filter(a => a.bnb_balance > 0);
      console.log(`Found ${addressesWithBalance.length} addresses with BNB balance\n`);

      // Create address map
      const addressMap = this.createAddressMap(maxUserId);

      // Match addresses
      console.log('Matching addresses...\n');
      const recovered: RecoveredAddress[] = [];
      let matched = 0;
      let notFound = 0;

      for (const addressData of addressesWithBalance) {
        const key = addressData.bsc_wallet_address.toLowerCase();
        
        if (addressMap.has(key)) {
          const { userId, privateKey } = addressMap.get(key)!;
          recovered.push({
            userId,
            address: addressData.bsc_wallet_address,
            privateKey,
            bnbBalance: addressData.bnb_balance
          });
          matched++;
        } else {
          notFound++;
          console.log(`⚠ Not found: ${addressData.bsc_wallet_address}`);
        }
      }

      console.log(`\n✓ Matched: ${matched}`);
      console.log(`✗ Not found: ${notFound}`);
      console.log(`Total BNB: ${recovered.reduce((sum, a) => sum + a.bnbBalance, 0).toFixed(6)}\n`);

      return recovered;
    } catch (error) {
      console.error('Error reading addresses file:', error);
      throw error;
    }
  }

  /**
   * Save recovered addresses to file
   */
  saveRecovered(recovered: RecoveredAddress[], outputPath: string): void {
    const output = {
      recoveredAt: new Date().toISOString(),
      walletSeed: this.walletSeed,
      totalRecovered: recovered.length,
      totalBNB: recovered.reduce((sum, a) => sum + a.bnbBalance, 0),
      addresses: recovered
    };

    fs.writeFileSync(outputPath, JSON.stringify(output, null, 2));
    console.log(`✓ Saved to: ${outputPath}`);
    console.log(`\n⚠️  IMPORTANT: This file contains private keys!`);
    console.log(`   Delete it after transferring funds.\n`);
  }

  /**
   * Generate transfer script
   */
  generateTransferScript(
    recovered: RecoveredAddress[],
    targetAddress: string,
    outputPath: string
  ): void {
    const script = `#!/bin/bash
# Auto-generated transfer script
# This script transfers BNB from recovered addresses to: ${targetAddress}

${recovered.map((r, i) => `
# Transfer ${i + 1}/${recovered.length}: ${r.address} (${r.bnbBalance} BNB)
# Private Key: ${r.privateKey}
# Amount: ${Math.max(0, r.bnbBalance - 0.0001).toFixed(6)} BNB
`).join('\n')}

echo "To execute transfers, use the recovered_addresses.json file with your Web3 wallet or script."
`;

    fs.writeFileSync(outputPath, script);
    console.log(`✓ Transfer script template saved to: ${outputPath}\n`);
  }

  /**
   * Print summary table
   */
  printSummary(recovered: RecoveredAddress[]): void {
    console.log('\n' + '='.repeat(80));
    console.log('RECOVERY SUMMARY');
    console.log('='.repeat(80));
    console.log(`Total Recovered: ${recovered.length}`);
    console.log(`Total BNB: ${recovered.reduce((sum, a) => sum + a.bnbBalance, 0).toFixed(6)}`);
    console.log(`Wallet Seed: ${this.walletSeed}`);
    console.log('='.repeat(80));
    
    if (recovered.length > 0 && recovered.length <= 20) {
      console.log('\nRecovered Addresses:');
      console.log('-'.repeat(80));
      recovered.forEach((r, i) => {
        console.log(`${i + 1}. UserId: ${r.userId}`);
        console.log(`   Address: ${r.address}`);
        console.log(`   BNB: ${r.bnbBalance}`);
        console.log(`   Private Key: ${r.privateKey.substring(0, 10)}...`);
      });
    } else if (recovered.length > 20) {
      console.log(`\nShowing first 5 of ${recovered.length} addresses:`);
      console.log('-'.repeat(80));
      recovered.slice(0, 5).forEach((r, i) => {
        console.log(`${i + 1}. UserId: ${r.userId} | Address: ${r.address} | BNB: ${r.bnbBalance}`);
      });
      console.log(`... and ${recovered.length - 5} more`);
    }
    console.log('='.repeat(80) + '\n');
  }
}

// Main execution
async function main() {
  const args = process.argv.slice(2);
  
  // Parse arguments
  let walletSeed = 'default-seed';
  let maxUserId = 10000;
  let addressesFile = 'addresses_with_balances.json';
  
  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--seed' && args[i + 1]) {
      walletSeed = args[i + 1];
      i++;
    }
    if (args[i] === '--max-id' && args[i + 1]) {
      maxUserId = parseInt(args[i + 1]);
      i++;
    }
    if (args[i] === '--file' && args[i + 1]) {
      addressesFile = args[i + 1];
      i++;
    }
  }

  console.log('╔════════════════════════════════════════════════════════════════════════════════╗');
  console.log('║                      QUICK ADDRESS RECOVERY TOOL                              ║');
  console.log('╚════════════════════════════════════════════════════════════════════════════════╝\n');

  const recovery = new QuickRecovery(walletSeed);
  
  try {
    const filePath = path.join(__dirname, addressesFile);
    const outputPath = path.join(__dirname, 'recovered_addresses.json');
    const scriptPath = path.join(__dirname, 'transfer_template.sh');

    // Recover addresses
    const recovered = await recovery.recoverFromFile(filePath, maxUserId, walletSeed);

    // Save results
    recovery.saveRecovered(recovered, outputPath);

    // Generate transfer script template
    if (recovered.length > 0) {
      const targetAddress = '0x' + '0'.repeat(40); // Placeholder
      recovery.generateTransferScript(recovered, targetAddress, scriptPath);
    }

    // Print summary
    recovery.printSummary(recovered);

    console.log('NEXT STEPS:');
    console.log('1. Review recovered_addresses.json');
    console.log('2. Use the private keys to transfer BNB to your wallet');
    console.log('3. Delete recovered_addresses.json for security\n');

  } catch (error) {
    console.error('Fatal error:', error);
    process.exit(1);
  }
}

// Usage examples
console.log(`
USAGE:
  npx ts-node quick-recover.ts [options]

OPTIONS:
  --seed <value>      Wallet seed used during address generation (default: "default-seed")
  --max-id <number>   Maximum userId to search (default: 10000)
  --file <path>       Path to addresses JSON file (default: "addresses_with_balances.json")

EXAMPLES:
  npx ts-node quick-recover.ts
  npx ts-node quick-recover.ts --seed my-custom-seed --max-id 50000
  npx ts-node quick-recover.ts --file my_addresses.json

`);

main().catch(console.error);
